export default async (context, locale) => {
  return await Promise.resolve({
    home: {
      title: "جامعة صلاح الدين",
      description:
        "الموقع الرسمي لأطروحات جامعة صلاح الدين ، يمكنك هنا العثور على جميع الأوراق البحثية الرسمية للبكالوريوس والدكتوراه والماجستير للطلاب المتخرجين.",
      search: "البحث",
      searchWithDots: "البحث...",
      home: "الرئيسية",
      collagesTitle: "كليات جامعة صلاح الدين",
      bachelor: "بكالوريوس",
      collages: {
        science: "كلية العلوم",
        engineering: "كلية الهندسة",
        law: "كلية الحقوق",
        agriculture: "كلية الزراعة",
        education: "كلية التربية",
        arts: "كلية الفنون",
        languages: "كلية اللغات",
        administrationAndEconomics: "كلية الإدارة والاقتصاد",
        basicEducation: "كلية التربية الاساسية",
        physicalEducation: "كلية التربية الرياضية",
        islamicScience: "كلية العلوم الإسلامية",
        fineArts: "كلية الفنون الجميلة",
        educationShaqlawa: "كلية التربية شقلاوة",
        educationMakhmur: "كلية التربية مخمور",
        politicalScience: "كلية العلوم السياسية",
      },
      thesisDegreeNewsTitle: "أحدث درجات الرسالة",
      collageOf: "كلية",
      fullArticle: "انظر جميع المقالات",
      seeFullArticle: "انظر جميع المقالات",
      latestNews: "أحدث الأخبار",
      thesisDegreeNewsTitle2: "عن جامعة صلاح الدين",
      thesisDetail:
        "جامعة صلاح الدين - أربيل هي واحدة من مؤسسات التعليم العالي الحكومية في شمال العراق وخاصة إقليم كردستان. تقع في أربيل ، عاصمة إقليم الأكراد المتمتع بالحكم الذاتي في العراق. تأسست جامعة السليمانية - السليمانية عام 1968.",
      mainWebsite: "الموقع الرئيسي",
      footer: "@٢٠٢٢ جامعة صلاح الدين أطروحة. كل الحقوق محفوظة.",
      notFound: "الصفحة غير موجودة",
      pageName: "موقع جامعة صلاح الدين للرسائل الجامعية",
    },
    thesis: {
      title: "تصفية البحث",
      searchPlaceholder: "البحث...",
      allDegreesPlaceholder: "كل الدرجات",
      allDepartments: "جميع الإدارات",
      pageTitle: "أطروحات",
      allCollages: "جميع الكليات",
      pageName: "موقع جامعة صلاح الدين للرسائل الجامعية",
      pageDescription:
        "صفحة رسائل جامعة صلاح الدين ، تصفية حسب الدرجة ، القسم ، الكلية ، البحث ، والمزيد",
      noResults: "لم يتم العثور على أطروحة",
      noMatch: "آسف ، لا توجد خيارات مطابقة.",
      noOption: "لا توجد خيارات هنا...",
    },
    thesisDetail: {
      contactInfo: "معلومات الاتصال بالطالب",
      name: "اسم",
      email: "البريد الإلكتروني",
      degreeType: "نوع الشهادە",
      collage: "كلية",
      phone: "هاتف",

      department: "القسم",
      similarResearches: "ابحاث مماثلة",
    },
  });
};
