export default async (context, locale) => {
  return await Promise.resolve({
    home: {
      title: "توێژینەوەکانی زانکۆی سەڵاحەدین",
      description:
        "ماڵپەڕی فەرمی توێژینەوەکانی  زانکۆی سەلاحەدین ، کە دەتوانیت هەموو توێژینەوە فەرمییەکانی بەکالۆریۆس، دکتۆرا، و ماستەر لە خوێندکارە دەرچووەکان پێشان بات",
      search: "گەڕان",
      searchWithDots: "گەڕان...",
      home: "سەرەکی",
      collagesTitle: "کۆلێژەکانی زانکۆی سەڵاحەدین",
      bachelor: "بەکالۆریۆس",
      collages: {
        science: "کۆلێژی زانست",
        engineering: "کۆلێژی ئەندازیاری",
        law: "کۆلێژی یاسا",
        agriculture: "کۆلێژی کشتوکاڵ",
        education: "کۆلێژی پەروەردە",
        arts: "کۆلێژی هونەرە جوانەکان",
        languages: "کۆلێژی زمانەکان",
        administrationAndEconomics: "کۆلێژی کارگێڕی و ئابووری",
        basicEducation: "کۆلێژی پەروەردەی بنەڕەتی",
        physicalEducation: "کۆلێژی پەروەردەی وەرزشی",
        islamicScience: "کۆلێژی زانستی ئیسلامی",
        fineArts: "کۆلێژی هونەرە جوانەکان",
        educationShaqlawa: "کۆلێژی پەروەردەی شەقڵاوە",
        educationMakhmur: "کۆلێژی پەروەردەی مەخمور",
        politicalScience: "کۆلێژی زانستە سیاسیەکان",
      },
      thesisDegreeNewsTitle: "نوێترین توێژینەوەکان",
      collageOf: "كۆلێژی",
      fullArticle: "سەیری هەموو بابەتەکان بکە",
      seeFullArticle: "درێژەی بابەت",
      latestNews: "نوێترین هه‌واڵ",
      thesisDegreeNewsTitle2: "دەربارەی زانکۆی سەڵاحەدین",
      thesisDetail:
        "زانکۆی سەڵاحەدین-هەولێر یەکێکە لە دامەزراوە گشتیەکانی خوێندنی باڵا لە باکووری عێراق و بەتایبەتی هەرێمی کوردستان. دەكەوێتە شاری هەولێری پایتەختی هەرێمی خۆسەری كوردی عێراق. زانکۆی سلێمانی-سلێمانی لە ساڵی 1968 دامەزراوە.",
      mainWebsite: "ماڵپەڕی سەرەکی سەڵاحەدین",
      footer: "@٢٠٢٢ توێژینەوەی زانکۆی سەڵاحەدین. هەموو مافەکانی پارێزراوە.",
      notFound: "لاپەڕەکە نەدۆزرایەوە",
      pageName: "وێبسایتی توێژینەوەی زانکۆی سەڵاحەدین",
    },
    thesis: {
      title: "گەڕان & فلتەرکردن",
      searchPlaceholder: "گەڕان...",
      allDegreesPlaceholder: "هەموو پلەکان",
      allDepartments: "سەرجەم بەشەکان",
      allCollages: "سەرجەم کۆلێژەکان",
      allSupervisors: "سەرجەم سەرپەرشتیارەکان",
      pageTitle: "توێژینەوەکان",
      pageName: "ماڵپەڕی تێزەکانی زانکۆی سەڵاحەدین",
      pageDescription:
        "پەیجی توێژینەوەكان زانکۆی سەڵاحەدین، فلتەر بەپێی بڕوانامە، بەش، کۆلاج، گەڕان، و زۆر شتی تر",
      noMatch: "ببورە، هیچ بژاردەیەکی هاوتا نییە.",
      noResults: "هیچ توێژینەوەیەک نەدۆزرایەوە",
      noOption: "هیچ بژاردەیەک نییە...",
    },
    thesisDetail: {
      contactInfo: "زانیاری توێژەوە",
      name: "ناو",
      email: "ئیمەیڵ",
      phone: "تەلەفۆن",
      degreeType: "جۆری بڕوانامە",
      collage: "کۆلێژ",
      similarResearches: "توێژینەوە هاوشێوەکان",
      supervisors: "سەرپەرشتیارەکان",
      supervisor: "سەرپەرشتیار",
      department: "بەش",
    },
  });
};
